### PR TITLE
load plugin files with specified suffix only

### LINKED ISSUE #1470: Bug Report: Plugin Loader will error on *.conf
### Summary
Qt automatically generates *.conf for builtin plugin DLLs on Windows. Every time Qv2ray runs, the file is automatically generated and next time you open Qv2ray, the error will occur.

### Expected behavior
Don't load *.conf files.

### How to Reproduce
1. Download a clean release and extract.
2. Run it, then close it.
3. Run it --- the dialog appears.

### Screenshots
图片

### Additional Info
_Add any other context about the problem here._

### PR DESCRIPTION
**Pull request by dyhkwong**
> GitHub Magic: Fixes #1470

### CODE REVIEW

File: src/components/plugins/QvPluginHost.cpp [hunk 1]
```diff
@@ -35,6 +35,10 @@ namespace Qv2ray::components::plugins
             const QStringList entries = QDir(pluginDirPath).entryList(QDir::Files);
             for (const auto &fileName : entries)
             {
+                if (!fileName.endsWith(QV2RAY_LIBRARY_SUFFIX))
+                {
+                    continue;
+                }
```
Comment (DuckSoft) [inline src/components/plugins/QvPluginHost.cpp]:
```suggestion
                if (!fileName.endsWith(QV2RAY_LIBRARY_SUFFIX))
                {
                    DEBUG("Skipping: " + fileName + " in: " + pluginDirPath);
                    continue;
                }
```

**Review by DuckSoft — APPROVED** [review]

**Review by DuckSoft — APPROVED** [review]

**Comment by DuckSoft** [comment]
LGTM. Let's merge this.
Don't forget to bump BUILDVERSION.
